### ISSUE TITLE
building the-serenity-book locally

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/the-serenity-book#6]
This is a bit of a basic question but perhaps to log here as an issue to hopefully help others in future. I'm in the process of contributing to [the serenity book](https://serenity-bdd.github.io/theserenitybook/0.1.0/index.html) but I want to be able to preview the book locally with my pre-committed changes, so I can check for formatting and errors. 

I understand that the book uses [antora](https://antora.org/) to generate the book as a whole, as the book is written in [Asciidoctor](https://asciidoctor.org/). So I think this is a extent of the installation steps I need:
- Checked out the following git repos into my workspace as siblings to each other:
  - https://github.com/serenity-bdd/the-serenity-book.git
  - https://github.com/serenity-bdd/serenity-docs.git 
- Installed (at least) node version 8 
  - nvm install 8
  - nvm use 8 -> Now using node v8.11.4 (npm v5.6.0)
- globally installed asciidoctor and antora:
  - `brew install asciidoctor`
  - `npm i -g @antora/cli`
- from `the-serenity-book` git directory:  
  - `npm i @antora/site-generator-default`
- from `serenity-docs` git directory:  
  - `npm i @antora/site-generator-default`

Then I:
- made the various adoc changes locally in `the-serenity-book` location `modules/ROOT/pages/`
-  ran this command to generate content into the build folder:
  - `asciidoctor modules/ROOT/pages/*.adoc -D build -a imagesdir=assets/images`
- temporarily edited `url` property in `serenity-docs/site.yml` to point to my local project as follows:
```
site:
  title: The Serenity BDD Book
content:
  sources:
#  - url: https://github.com/serenity-bdd/the-serenity-book.git
   - url: ../the-serenity-book
#    branches: master
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: themes/serenity-antora-theme.zip
    snapshot: true

runtime:
  pull: true
```
- ran the command in `serenity-docs` as follows:
  - antora site.yml 

But the content output to `serenity-docs/build/site/theserenitybook/0.1.0` is still not the up to date content!

Please can you point out the error of my ways? Oddly enough my recent PRs #5 and #4 found their way successfully to the [published output](https://serenity-bdd.github.io/theserenitybook/0.1.0/serenity-parallel.html#_configuring_and_running_batched_cucumber_test_suites_from_maven), so this is just a local build problem I'm having 😞
